### PR TITLE
Gh actions fix

### PR DESCRIPTION
**Pull request by vraravam**
Fix for the missing git configs

### CODE REVIEW

**Review by vantezzen — APPROVED** [review]
You should now also be able to merge these yourself now. Sorry, I though I already gave you access to that

**Comment by vantezzen** [comment]
```
info Done building in 27.626978783 sec
fatal: could not read Username for 'https://github.com': No such device or address

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ferdi-website@0.1.0 ci-deploy: `gatsby build && cp ./CNAME public/ && gh-pages -d public -r https://$GH_TOKEN@github.com/getferdi/website.git`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ferdi-website@0.1.0 ci-deploy script.
npm
```

Is this related to this fix?

**Comment by vraravam** [comment]
> ```
> info Done building in 27.626978783 sec
> fatal: could not read Username for 'https://github.com': No such device or address
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ferdi-website@0.1.0 ci-deploy: `gatsby build && cp ./CNAME public/ && gh-pages -d public -r https://$GH_TOKEN@github.com/getferdi/website.git`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the ferdi-website@0.1.0 ci-deploy script.
> npm
> ```
> 
> Is this related to this fix?

It looks like the `GH_TOKEN` is still coming up as empty: 
Screenshot 2021-07-18 at 11 33 55 PM

**Comment by vraravam** [comment]
Maybe for this time around - can we manually publish the website changes? I will take a look at this issue tomorrow (its 11:40 pm here in India)

**Comment by vantezzen** [comment]
Weird, it should be added here:

Screenshot 2021-07-18 at 20 08 22

Or ist GitHub Action just hiding it from the log?

**Comment by vantezzen** [comment]
Of course. I can merge your changes but don't currently have the local env set up, could you create a PR for the deployment, too?

**Comment by vraravam** [comment]
Yes - but, the same code from the main repo, shows with asterisks:
Screenshot 2021-07-18 at 11 40 20 PM
 - which is why I suspect something about the secrets being set here for this repo. Let me take a look later tomorrow for fixing this.

**Comment by vantezzen** [comment]
Screenshot 2021-07-18 at 20 13 33

I can actually see them in the main branch so it might just be something with that.

**Comment by vantezzen** [comment]
Ok, looks like this was just a problem with the branching and GitHub Actions as the Action ran through on the master branch - so no need to raise a deployment PR anymore

**Pull request merged**
